[package]
name = "tcvm"
version = "0.1.0"
edition = "2024"

[dependencies]
hashbrown = { version = "0.15.4", default-features = false, features = ["nightly"] }
foldhash = { version = "0.1.5", default-features = false }
paste = "1.0.15"
