[package]
name = "tcvm"
version = "0.1.0"
edition = "2024"

[dependencies]
foldhash = { version = "0.1.5", default-features = false }
hashbrown = { version = "0.15.4", default-features = false, features = ["nightly"] }
gc-arena = "0.5.3"
paste = "1.0.15"
